spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8081

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**,/user/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter
        - id: market-data-service
          uri: lb://market-data-service
          predicates:
            - Path=/market/**
          filters:
            - AuthenticationFilter
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**
          filters:
            - AuthenticationFilter
        - id: order-validation
          uri: lb://order-validation
          predicates:
            - Path=/validation/**
          filters:
            - AuthenticationFilter

jwt:
  secret: 743777217A25432A462D4A614E645267556B58703273357638782F413F442847