spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8081

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: tradeX-rest-api
            client-secret: Hl0t06h5BF3vOz9aTRUUYcl5N9Vcek0F
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:5000/login/oauth2/code/keycloak

        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/TradeX/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/TradeX/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/TradeX/protocol/openid-connect/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8080/realms/TradeX/protocol/openid-connect/certs
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/TradeX



#          keycloak-provider:
#            issuer-uri: http://localhost:8080/realms/TradeX

#        registration:
#          keycloak-spring-gateway:
#            provider: keycloak-provider
#            client-id: tradeX-rest-api
#            client-secret: lo1F8PvkGOyqIdseMlgjALFTgIduunQ1
#            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'